engines:
  eslint:
    enabled: true
  nodesecurity:
    enabled: true 
  fixme:
    enabled: true
  duplication:
    enabled: false 
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
ratings:
- lib/**
- index.js
exclude_paths:
- spec/**/*
- data/**
- static/**
